spring.application.name=Shopping-Cart
spring.datasource.url=jdbc:mysql://localhost:3306/shoppingcart?useSLL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

###########setup for mailing###############
spring.mail.host=smtp.gmail.com

#App email
spring.mail.username=senderemail_withgmailapppassword@gmail.com
#App password from gmail
spring.mail.password=apppasswordinserthere

spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###########setup for mailing###############